name: Check

on:
    pull_request:
        branches: ["main"]

jobs:
    code-check:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4.1.1
            - uses: actions/setup-node@v4
              with:
                  node-version: "20"
            - name: Install dependencies
              run: npm ci
            - name: Check project files
              run: npm run check
            - name: Build project
              run: npm run build
