name: Check

on:
    pull_request:
        branches: ["main"]

jobs:
    code-check:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4.1.7
            - uses: oven-sh/setup-bun@v1
            - name: Install dependencies
              run: bun install
            - name: Check project files
              run: bun run check
            - name: Type check project files
              run: bun run type-check
            - name: Build project
              run: bun run build
