name: Publish

on:
    push:
        branches: ["main"]

jobs:
    code-check:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4.2.2
            - uses: oven-sh/setup-bun@v2
            - name: Install dependencies
              run: bun install
            - name: Check project files
              run: bun run check
            - name: Type-check project files
              run: bun run type-check
            - name: Build project
              run: bun run build
            - name: Upload build files
              uses: actions/upload-artifact@v4
              with:
                  name: build-files
                  path: dist/

    docker-build:
        runs-on: ubuntu-latest
        needs: [code-check]
        timeout-minutes: 20
        steps:
            - name: Check out repo
              uses: actions/checkout@v4.2.2

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Download build files
              uses: actions/download-artifact@v4
              with:
                  name: build-files
                  path: dist

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: true
                  tags: leondeklerk/mqtt-stats-aggregator:latest,leondeklerk/mqtt-stats-aggregator:${{ github.SHA }}
                  platforms: "linux/amd64"
